In [1]:
#-*- coding: euc-kr -*-

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from pandas import DataFrame, Series

%matplotlib inline

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
path = 'challenge_data/'

data = pd.read_csv(path + 'Data_set.csv', encoding = 'euc-kr')
test = pd.read_csv(path + 'Test_set.csv', encoding = 'euc-kr')

In [3]:
data.describe()

,CUST_ID,TARGET,BNK_LNIF_CNT,CPT_LNIF_CNT,SPART_LNIF_CNT,ECT_LNIF_CNT,TOT_LNIF_AMT,TOT_CLIF_AMT,BNK_LNIF_AMT,CPT_LNIF_AMT,CRDT_OCCR_MDIF,SPTCT_OCCR_MDIF,CRDT_CARD_CNT,CTCD_OCCR_MDIF,CB_GUIF_CNT,CB_GUIF_AMT,CUST_JOB_INCM,HSHD_INFR_INCM,ACTL_FMLY_NUM,CUST_FMLY_NUM,LAST_CHLD_AGE,MATE_JOB_INCM,CRDT_LOAN_CNT,MIN_CNTT_DATE,TOT_CRLN_AMT,TOT_REPY_AMT,CRLN_OVDU_RATE,CRLN_30OVDU_RATE,LT1Y_CLOD_RATE,STRT_CRDT_GRAD,LTST_CRDT_GRAD,PREM_OVDU_RATE,AVG_STLN_RATE,STLN_REMN_AMT,LT1Y_STLN_AMT,LT1Y_SLOD_RATE,GDINS_MON_PREM,SVINS_MON_PREM,FMLY_GDINS_MNPREM,FMLY_SVINS_MNPREM,MAX_MON_PREM,TOT_PREM,FMLY_TOT_PREM,CNTT_LAMT_CNT,LT1Y_CTLT_CNT,AUTR_FAIL_MCNT,FYCM_PAID_AMT,FMLY_CLAM_CNT,FMLY_PLPY_CNT,AVG_CALL_TIME,AVG_CALL_FREQ,ARPU,MON_TLFE_AMT,MOBL_FATY_PRC,TEL_CNTT_QTR,NUM_DAY_SUSP,CRMM_OVDU_AMT,TLFE_UNPD_CNT,LT1Y_MXOD_AMT,MOBL_PRIN
count,100233.000000,100233.00000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,99206.000000,100233.000000,100233.000000,100233.000000,1.002330e+05,1.002330e+05,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,1.002330e+05,1.002330e+05,100233.000000,1.002330e+05,1.002330e+05,1.002330e+05,1.002330e+05,1.002330e+05,1.002330e+05,1.002330e+05,100233.000000,100233.000000,100233.000000,1.002330e+05,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,100233.000000,1.002330e+05,100233.000000,100233.000000,1.002330e+05,100233.000000,1.002330e+05,1.002330e+05
mean,51124.199445,0.04277,0.840192,0.500873,0.953029,0.477986,84042.832530,33202.187703,51648.838237,4185.885108,18.080203,13.991669,3.092285,91.004200,0.096256,9183.099508,2788.233416,6922.486606,2.757794,1.392565,12.233958,1719.524508,0.162232,19743.957130,1.182315e+06,8.709208e+05,2.522213,0.225295,0.188760,0.149222,0.293147,8.010386,16.954666,1.603045e+06,9.275787e+05,2.584478,1.276526e+05,9.204713e+04,1.840117e+05,1.364362e+05,3.734214e+05,2.071504e+07,3.077308e+07,0.115351,0.022757,2.716082,4.039838e+06,4.218092,1.235092,281.697764,169.051560,43808.226582,72478.225734,5.302196e+05,20121.889418,17.075803,1.105784e+04,0.003681,1.919099e+04,1.902293e+05
std,29522.979407,0.20234,0.734242,0.838422,1.138649,0.707598,127511.859603,83070.276370,95759.025724,13035.386223,29.095001,28.687146,1.829295,41.957547,0.523791,78569.076446,2472.287102,2996.156129,1.316862,0.618116,13.964236,2460.475232,0.612144,59751.358139,5.318477e+06,4.372416e+06,12.153939,3.170039,3.182262,0.800191,1.317122,11.910593,34.314664,5.771587e+06,5.754817e+06,9.149192,2.349951e+05,3.153750e+05,3.181124e+05,4.993498e+05,7.019720e+05,4.482214e+07,6.431527e+07,0.454317,0.202228,6.945916,1.456263e+07,9.199485,1.642505,359.802971,168.267016,21601.205966,61274.558190,3.829765e+05,36.601678,128.154630,4.799994e+04,0.063929,7.100469e+04,2.350795e+05
min,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000e+00,19934.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
25%,25557.000000,0.00000,0.000000,0.000000,0.000000,0.000000,12001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,61.000000,0.000000,0.000000,0.000000,4800.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+04,5.000000e+06,6.000000e+06,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,69.000000,41.000000,30000.000000,40000.000000,0.000000e+00,20113.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
50%,51119.000000,0.00000,1.000000,0.000000,1.000000,0.000000,39001.000000,9001.000000,9001.000000,0.000000,1.000000,0.000000,3.000000,121.000000,0.000000,0.000000,3600.000000,6600.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,5.000000e+04,0.000000e+00,8.000000e+04,0.000000e+00,1.900000e+05,1.100000e+07,1.500000e+07,0.000000,0.000000,0.000000,3.000000e+05,1.000000,1.000000,171.000000,135.000000,40000.000000,60000.000000,7.000000e+05,20132.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,1.000000e+05
75%,76691.000000,0.00000,1.000000,1.000000,1.000000,1.000000,105001.000000,30001.000000,63001.000000,3001.000000,25.000000,13.000000,4.000000,121.000000,0.000000,0.000000,4700.000000,9200.000000,4.000000,2.000000,24.000000,4400.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,1.600000e+05,0.000000e+00,2.300000e+05,1.000000e+05,3.900000e+05,2.300000e+07,3.400000e+07,0.000000,0.000000,2.000000,1.900000e+06,5.000000,2.000000,361.000000,242.000000,60000.000000,80000.000000,9.000000e+05,20143.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,3.200000e+05
max,102252.000000,1.00000,5.000000,5.000000,7.000000,6.000000,994001.000000,994001.000000,944001.000000,301001.000000,121.000000,121.000000,11.000000,121.000000,10.000000,980001.000000,10000.000000,20000.000000,8.000000,5.000000,60.000000,10000.000000,11.000000,201604.000000,1.010000e+08,1.010000e+08,100.000000,100.000000,100.000000,7.000000,10.000000,100.000000,100.000000,1.010000e+08,1.010000e+08,100.000000,4.000000e+06,4.000000e+06,4.000000e+06,1.000000e+07,1.000000e+07,1.000000e+09,1.000000e+09,7.000000,6.000000,61.000000,3.001000e+08,171.000000,22.000000,10000.000000,1900.000000,500000.000000,950000.000000,1.200000e+06,20162.000000,2700.000000,1.200000e+06,2.000000,1.600000e+06,1.100000e+06

In [3]:
data['OCCP_NAME_G'] = data['OCCP_NAME_G'].replace('*', 'missing') 

data['OCCP_NAME_G'].replace(' ', '', regex=True, inplace=True)

In [17]:
print(data.OCCP_NAME_G.isnull().sum())
print(data.CUST_JOB_INCM.isnull().sum())
print(data.HSHD_INFR_INCM.isnull().sum())
print(data.ACTL_FMLY_NUM.isnull().sum())

0
0
0
0

In [9]:
data['OCCP_NAME_G'].fillna('missing', inplace=True)

In [21]:
data.head(100)

,CUST_ID,TARGET,BNK_LNIF_CNT,CPT_LNIF_CNT,SPART_LNIF_CNT,ECT_LNIF_CNT,TOT_LNIF_AMT,TOT_CLIF_AMT,BNK_LNIF_AMT,CPT_LNIF_AMT,CRDT_OCCR_MDIF,SPTCT_OCCR_MDIF,CRDT_CARD_CNT,CTCD_OCCR_MDIF,CB_GUIF_CNT,CB_GUIF_AMT,OCCP_NAME_G,CUST_JOB_INCM,HSHD_INFR_INCM,ACTL_FMLY_NUM,CUST_FMLY_NUM,LAST_CHLD_AGE,MATE_OCCP_NAME_G,MATE_JOB_INCM,CRDT_LOAN_CNT,MIN_CNTT_DATE,TOT_CRLN_AMT,TOT_REPY_AMT,CRLN_OVDU_RATE,CRLN_30OVDU_RATE,LT1Y_CLOD_RATE,STRT_CRDT_GRAD,LTST_CRDT_GRAD,PREM_OVDU_RATE,LT1Y_PEOD_RATE,AVG_STLN_RATE,STLN_REMN_AMT,LT1Y_STLN_AMT,LT1Y_SLOD_RATE,GDINS_MON_PREM,SVINS_MON_PREM,FMLY_GDINS_MNPREM,FMLY_SVINS_MNPREM,MAX_MON_PREM,TOT_PREM,FMLY_TOT_PREM,CNTT_LAMT_CNT,LT1Y_CTLT_CNT,AUTR_FAIL_MCNT,FYCM_PAID_AMT,FMLY_CLAM_CNT,FMLY_PLPY_CNT,AGE,SEX,AVG_CALL_TIME,AVG_CALL_FREQ,TEL_MBSP_GRAD,ARPU,MON_TLFE_AMT,CBPT_MBSP_YN,MOBL_FATY_PRC,TEL_CNTT_QTR,NUM_DAY_SUSP,CRMM_OVDU_AMT,TLFE_UNPD_CNT,LT1Y_MXOD_AMT,PAYM_METD,LINE_STUS,MOBL_PRIN,OCCP_NAME_G_le
0,1,0,1,0,0,0,9001,9001,9001,0,1,0,2,13,3,420001,공무원,5400,7700,4,1,24.0,주부,0,0,0,0,0,0,0,0,0,0,12,20미만,0,0,0,0,190000,0,190000,0,190000,20000000,20000000,0,0,10,0,0,0,50,1,450,493,NaN,30000,80000,N,800000,20111,0,0,0,0,O,U,580000,2
1,2,0,1,0,0,0,24001,0,24001,0,0,0,2,121,0,0,자영업,5500,8100,4,2,29.0,주부,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,110000,0,0,7000000,36000000,0,0,0,300000,2,5,50,1,81,22,NaN,30000,40000,N,500000,20143,0,0,0,0,O,U,90000,13
2,3,0,0,1,3,2,15001,9001,0,3001,1,25,4,121,0,0,주부,0,4900,4,1,34.0,2차산업 종사자,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,100000,11000000,11000000,0,0,0,0,0,2,60,2,139,17,NaN,30000,40000,Y,500000,20103,0,0,0,0,O,U,120000,15
3,4,1,0,2,4,2,6001,3001,0,3001,1,25,4,61,0,0,학생,0,10100,2,1,0.0,-,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,4000000,4000000,0,0,0,0,0,1,35,1,1118,0,NaN,30000,80000,N,900000,20144,0,540000,0,630000,G,S,320000,16
4,5,0,4,0,0,0,21001,15001,21001,0,1,0,1,97,0,0,공무원,4800,4800,4,1,14.0,주부,0,0,0,0,0,0,0,0,0,0,0,0,95,2000000,0,0,0,0,0,0,300000,4000000,4000000,0,0,0,500000,2,1,45,1,396,354,W,50000,80000,Y,800000,20131,0,130000,0,90000,G,U,410000,2
5,6,0,1,0,1,1,141001,27001,111001,0,1,1,4,121,0,0,산업종사자3차,4400,7700,2,2,0.0,단순 사무직,3300,0,0,0,0,0,0,0,0,0,25,0,0,0,0,0,100000,0,190000,0,190000,1000000,6000000,0,0,0,300000,1,1,45,1,268,179,Q,60000,80000,N,400000,20154,0,0,0,0,O,U,170000,10
6,7,0,0,1,2,1,12001,3001,0,9001,121,121,2,121,1,6001,주부,0,7700,5,3,19.0,2차산업 종사자,4400,1,200106,4000000,4000000,81,14,0,0,0,71,10미만,94,3000000,2000000,10,0,200000,300000,200000,200000,11000000,33000000,0,0,1,800000,0,0,40,2,744,535,W,50000,120000,N,900000,20143,0,120000,0,290000,G,U,720000,15
7,8,0,1,0,0,0,3001,3001,3001,0,1,0,2,121,0,0,기업_단체임원,0,10300,3,1,24.0,사무직,5000,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,60000,4000000,4000000,0,0,0,0,0,1,60,1,309,221,R,10000,70000,Y,900000,20021,0,0,0,0,O,U,40000,3
8,9,0,2,0,0,0,273001,273001,273001,0,37,0,5,121,0,0,주부,0,7600,4,1,9.0,전문직,5400,0,0,0,0,0,0,0,0,0,3,10미만,0,0,0,0,0,60000,0,60000,60000,2000000,2000000,0,0,0,0,0,0,40,2,314,179,R,60000,70000,Y,0,20131,0,0,0,0,O,U,0,15
9,10,0,0,1,1,0,9001,9001,0,9001,1,1,3,25,0,0,단순사무직,4700,12400,4,1,14.0,기업/단체 임원,7500,0,0,0,0,0,0,0,0,0,15,10미만,99,0,3000000,30,300000,0,300000,0,340000,36000000,36000000,0,0,21,300000,1,2,40,1,0,0,NaN,0,0,N,800000,20133,0,0,0,0,O,U,0,6
10,11,1,0,3,5,2,27001,27001,0,18001,1,25,4,61,0,0,주부,0,11300,3,1,24.0,자영업,6200,0,0,0,0,0,0,0,0,0,1,10미만,0,0,0,0,30000,0,30000,0,590000,1000000,1000000,0,0,2,0,0,0,55,2,17,5,NaN,40000,80000,N,900000,20062,0,0,0,0,R,U,470000,15
11,12,0,0,1,2,1,9001,6001,0,1,49,49,6,121,0,0,주부,0,9200,2,1,0.0,전문직,5300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40000,0,40000,0,40000,3000000,3000000,0,0,0,0,0,0,40,1,766,551,R,70000,380000,N,900000,20133,0,0,0,0,O,U,90000,15
12,13,0,1,0,0,0,12001,12001,12001,0,13,0,0,0,0,0,학생,0,5900,3,2,0.0,-,0,0,0,0,0,0,0,0,0,0,40,0,98,3000000,1000000,0,190000,0,230000,0,390000,9000000,14000000,0,0,31,32400000,0,0,25,2,343,182,W,60000,120000,Y,800000,20141,0,0,0,0,O,U,810000,16
13,14,0,2,0,0,0,201001,6001,201001,0,13,0,4,121,0,0,사무직,4700,8000,2,1,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30000,3000000,3000000,0,0,0,100000,1,1,40,1,547,184,W,60000,100000,N,900000,20151,0,0,0,0,K,U,330000,7
14,15,0,3,1,1,0,15001,9001,9001,3001,13,0,3,37,0,0,학생,0,5500,3,1,0.0,-,0,0,0,0,0,0,0,0,0,0,43,50미만,0,0,0,0,50000,0,50000,0,50000,1000000,1000000,0,0,2,0,0,0,25,2,398,140,Q,30000,70000,N,900000,20144,0,0,0,0,K,U,300000,16
15,16,0,1,0,1,1,339001,0,111001,0,0,0,0,0,0,0,주부,0,4900,5,1,19.0,2차산업 종사자,4400,0,0,0,0,0,0,0,0,0,6,10미만,46,1000000,0,40,340000,0,340000,0,340000,17000000,17000000,0,0,13,0,0,0,30,1,169,10,Q,60000,140000,N,500000,20142,0,0,0,0,O,U,40000,15
16,17,0,1,0,3,3,39001,9001,3001,0,1,121,3,61,0,0,주부,0,11000,4,2,19.0,사무직,6200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,990000,300000,18000000,76000000,0,0,0,0,0,1,55,2,5,0,NaN,20000,0,N,0,20092,0,0,0,0,NaN,U,0,15
17,18,0,1,0,0,0,273001,0,273001,0,0,0,6,121,0,0,단순노무직,3600,10600,2,2,0.0,주부,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60000,7000000,12000000,0,0,0,300000,3,2,60,2,239,30,NaN,50000,80000,N,1000000,20102,0,0,0,0,O,U,280000,5
18,19,0,1,0,0,0,18001,18001,18001,0,37,0,5,121,0,0,주부,0,7400,4,1,19.0,2차산업 종사자,5600,0,0,0,0,0,0,0,0,0,2,10미만,0,0,0,0,390000,110000,390000,110000,590000,41000000,41000000,0,0,0,500000,4,1,45,2,0,106,Q,10000,20000,Y,300000,20142,0,0,0,0,K,U,30000,15
19,20,0,2,0,1,1,174001,42001,129001,0,25,0,2,121,0,0,산업종사자3차,4300,11000,2,1,0.0,전문직,6800,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40000,6000000,6000000,0,0,0,0,0,1,50,2,273,93,NaN,50000,80000,N,900000,20143,0,0,0,0,O,U,130000,10
20,21,0,0,0,1,1,165001,0,0,0,37,37,3,121,0,0,학생,0,0,3,1,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30000,0,30000,30000,1000000,1000000,0,0,0,0,0,0,35,1,249,395,R,70000,80000,Y,1000000,20131,0,0,0,0,K,U,0,16
21,22,0,0,0,1,1,108001,108001,0,0,13,13,1,1,0,0,주부,0,6000,3,2,4.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,70000,0,490000,0,70000,6000000,30000000,0,0,0,14600000,31,0,35,2,551,487,R,50000,60000,Y,0,20122,0,0,0,0,K,U,0,15
22,23,0,0,0,1,1,180001,180001,0,0,25,85,0,0,0,0,missing,3700,7400,5,2,NaN,missing,3700,0,0,0,0,0,0,0,0,0,22,30미만,0,0,0,0,90000,0,230000,0,90000,9000000,40000000,0,0,10,200000,0,1,*,*,405,192,Q,30000,30000,Y,0,20114,0,0,0,0,K,U,0,0
23,24,0,0,1,2,1,51001,0,0,1,0,0,1,121,0,0,missing,0,0,2,1,0.0,주부,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9000000,9000000,0,0,0,50400000,6,0,*,*,550,280,W,40000,80000,N,800000,20102,2,80000,0,80000,O,U,470000,0
24,25,0,1,0,0,0,192001,0,192001,0,0,0,2,121,0,0,주부,0,4700,4,1,24.0,전문직,4300,0,0,0,0,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,30000,4000000,4000000,0,0,0,1500000,14,1,55,1,240,272,NaN,30000,30000,Y,600000,20101,0,0,0,0,K,U,0,15
25,26,0,1,0,0,0,27001,27001,27001,0,121,0,3,121,0,0,사무직,4700,4700,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,100000,0,100000,100000,10000000,10000000,0,0,3,0,0,0,50,2,117,80,W,30000,60000,N,800000,20112,0,0,0,0,K,U,60000,7
26,27,0,0,0,1,1,6001,6001,0,0,0,0,3,121,0,0,고소득전문직,8400,8400,5,2,24.0,주부,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,90000,0,90000,0,1190000,10000000,109000000,0,0,0,0,0,2,60,2,728,91,W,40000,50000,Y,1000000,20121,0,0,0,0,K,U,0,1
27,28,0,1,0,0,0,39001,0,39001,0,0,0,3,73,0,0,자영업,5900,9100,4,1,24.0,주부,0,0,0,0,0,0,0,0,0,0,8,10미만,71,7000000,0,10,190000,0,190000,0,190000,28000000,28000000,0,0,2,0,0,1,60,1,444,289,NaN,60000,80000,Y,900000,20143,0,0,0,0,K,U,280000,13
28,29,0,3,0,0,0,315001,24001,315001,0,1,0,5,121,1,129001,학생,0,10800,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80000,0,80000,0,80000,3000000,3000000,0,0,0,0,0,0,45,2,69,39,W,20000,20000,Y,0,20122,0,0,0,0,K,U,0,16
29,30,0,0,0,1,1,3001,3001,0,0,37,37,3,37,1,18001,산업종사자3차,3500,3500,3,2,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80000,0,230000,0,150000,8000000,16000000,0,0,0,100000,0,0,30,1,746,314,R,70000,120000,Y,0,20133,0,0,0,0,O,U,330000,10
30,31,0,1,0,0,0,9001,9001,9001,0,49,0,4,121,0,0,공무원,5200,11700,3,1,24.0,전문직,6400,0,0,0,0,0,0,0,0,0,1,10미만,0,0,0,0,130000,0,130000,0,300000,24000000,24000000,0,0,1,0,0,1,55,2,69,64,NaN,40000,40000,N,0,20134,0,0,0,0,O,U,0,2
31,32,0,4,0,2,3,411001,210001,135001,0,1,37,3,121,0,0,자영업,5800,10500,2,1,0.0,주부,4800,0,0,0,0,0,0,0,0,0,2,10미만,0,0,0,0,40000,0,40000,0,40000,2000000,2000000,0,0,1,1100000,6,0,45,1,0,0,NaN,20000,20000,N,700000,20094,10,0,0,0,O,U,0,13
32,33,0,0,0,1,1,93001,93001,0,0,85,85,4,121,0,0,산업종사자2차,4800,7600,5,3,39.0,기타,0,3,201306,50000000,50000000,0,0,0,2,4,3,20미만,22,3000000,3000000,0,230000,0,1190000,0,230000,18000000,159000000,0,0,1,105000000,37,4,50,1,10,0,NaN,20000,0,Y,0,20084,0,0,0,0,NaN,U,0,9
33,34,0,0,0,1,1,6001,6001,0,0,13,37,1,121,0,0,산업종사자2차,4800,5800,3,1,19.0,주부,0,0,0,0,0,0,0,0,0,0,1,10미만,0,0,0,0,230000,0,230000,0,260000,15000000,15000000,0,0,0,0,0,0,50,2,177,208,NaN,30000,40000,N,300000,20123,0,0,0,0,O,U,100000,9
34,35,0,1,0,0,0,198001,0,198001,0,0,0,5,121,0,0,주부,0,10100,4,1,34.0,-,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,140000,0,140000,0,140000,16000000,16000000,0,0,0,31800000,18,3,55,1,385,257,W,40000,40000,N,900000,20102,0,0,0,0,K,U,0,15
35,36,0,1,0,0,0,54001,54001,54001,0,13,0,2,61,0,0,사무직,3900,6200,2,1,0.0,-,0,0,0,0,0,0,0,0,0,0,6,10미만,0,0,0,0,0,340000,0,340000,590000,20000000,20000000,0,0,3,0,0,0,45,2,566,324,NaN,70000,120000,Y,900000,20152,0,10000,0,190000,O,U,50000,7
36,37,1,0,1,2,1,3001,3001,0,1,37,37,1,49,0,0,주부,0,4600,3,1,34.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,190000,0,190000,0,190000,5000000,5000000,0,0,0,25300000,2,0,35,1,17,0,W,70000,120000,N,900000,20123,0,120000,0,490000,G,U,460000,15
37,38,0,2,0,0,0,69001,0,69001,0,0,0,7,121,0,0,주부,0,4600,2,2,0.0,운전직,4600,0,0,0,0,0,0,0,0,0,44,60미만,100,3000000,2000000,60,200000,0,390000,0,260000,9000000,54000000,0,0,50,4200000,12,3,45,1,145,201,R,70000,140000,Y,900000,20143,0,0,0,0,K,U,300000,15
38,39,0,0,1,2,1,246001,0,0,15001,0,0,6,121,0,0,기업_단체임원,10000,10600,4,1,34.0,주부,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,140000,0,140000,1190000,89000000,89000000,0,0,0,1600000,4,3,55,2,399,455,R,60000,60000,Y,0,20134,0,0,0,0,O,U,0,3
39,40,0,1,1,1,0,96001,0,93001,1,0,0,6,121,0,0,산업종사자3차,3600,8800,4,1,24.0,자영업,5300,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,160000,0,160000,0,340000,6000000,6000000,0,0,0,200000,2,0,50,2,173,0,NaN,50000,180000,Y,500000,20151,0,180000,0,400000,G,U,130000,10
40,41,0,0,0,1,1,87001,87001,0,0,25,109,2,121,0,0,사무직,0,12900,2,1,0.0,주부,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,60000,8000000,8000000,0,0,0,0,0,1,65,1,2880,119,Q,50000,60000,Y,0,20144,0,0,0,0,K,U,30000,7
41,42,0,0,2,2,0,18001,18001,0,18001,1,13,5,121,0,0,단순사무직,3900,10000,4,2,0.0,사무직,6200,0,0,0,0,0,0,0,0,0,10,10미만,0,0,0,0,340000,0,340000,0,340000,15000000,22000000,0,0,2,7500000,10,2,35,2,224,111,Q,40000,40000,Y,0,20142,0,0,0,0,K,U,0,6
42,43,0,0,1,2,1,12001,12001,0,6001,1,25,2,121,0,0,기업_단체임원,5500,10500,4,1,24.0,2차산업 종사자,5100,0,0,0,0,0,0,0,0,0,37,0,0,0,0,0,0,0,0,0,80000,9000000,9000000,0,0,0,0,0,1,50,1,0,0,NaN,0,0,N,0,20134,0,0,0,0,O,U,0,3
43,44,0,1,0,0,0,3001,3001,3001,0,121,0,6,121,0,0,산업종사자2차,5600,9200,1,1,0.0,-,0,11,200908,23000000,23000000,0,0,0,4,5,9,10미만,100,3000000,10000000,0,340000,110000,340000,110000,790000,34000000,34000000,4,2,6,0,0,2,50,2,627,416,R,60000,80000,N,900000,20143,0,0,0,0,K,U,320000,9
44,45,0,1,1,3,2,6001,6001,1,1,37,61,1,61,0,0,산업종사자2차,5300,9600,4,2,14.0,사무직,4400,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,190000,0,40000,4000000,51000000,0,0,0,600000,0,3,45,1,170,64,NaN,60000,80000,N,0,20152,0,0,0,190000,O,U,260000,9
45,46,0,0,1,1,0,36001,36001,0,36001,25,25,5,121,0,0,주부,0,4600,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,30000,5000000,5000000,0,0,0,500000,3,1,60,1,110,250,NaN,50000,80000,Y,900000,19992,0,0,0,0,O,U,90000,15
46,47,1,0,1,2,1,3001,3001,0,1,121,121,1,121,0,0,자영업,3800,3800,2,1,24.0,-,0,1,200106,4000000,4000000,42,24,0,0,0,41,40미만,0,0,0,0,160000,0,160000,0,160000,2000000,2000000,2,1,14,0,0,0,50,2,74,113,W,60000,70000,N,0,20132,0,50000,0,0,O,U,0,13
47,48,0,1,4,4,0,30001,9001,9001,21001,25,0,7,121,0,0,산업종사자3차,3500,3500,2,1,9.0,-,0,0,0,0,0,0,0,0,0,0,20,40미만,0,0,0,0,50000,0,50000,0,50000,2000000,2000000,0,0,1,0,0,0,45,2,131,105,NaN,40000,70000,Y,0,20142,0,0,0,0,O,U,250000,10
48,49,0,0,0,2,2,24001,24001,0,0,1,49,0,0,1,18001,주부,0,3800,4,1,19.0,예체능계 종사자,3800,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,70000,8000000,8000000,0,0,0,400000,1,2,45,2,90,117,W,30000,40000,Y,300000,20111,0,0,0,0,O,U,90000,15
49,50,0,2,0,1,1,994001,117001,944001,0,37,97,3,109,7,980001,주부,0,7800,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,30000,6000000,6000000,0,0,0,0,0,1,60,2,0,0,NaN,10000,40000,N,900000,20144,148,0,0,0,O,S,270000,15
50,51,0,1,0,1,1,84001,9001,75001,0,49,49,3,121,1,9001,사무직,6000,7100,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,200000,0,200000,200000,1000000,1000000,0,0,0,0,0,0,50,2,137,287,R,50000,50000,N,900000,19993,0,0,0,0,G,U,0,7
51,52,0,1,2,2,0,300001,1,285001,15001,25,25,5,61,0,0,운전직,4100,6400,6,2,19.0,주부,0,0,0,0,0,0,0,0,0,0,56,30미만,100,1000000,0,10,120000,0,260000,0,390000,6000000,7000000,0,0,16,300000,4,0,45,1,30,98,NaN,30000,30000,N,200000,20112,0,0,0,0,K,U,60000,12
52,53,0,1,0,1,1,264001,108001,153001,0,13,13,6,97,0,0,사무직,4100,4200,3,1,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40000,0,40000,0,40000,7000000,7000000,0,0,0,0,0,0,40,1,105,225,W,40000,40000,Y,0,20133,0,0,0,0,K,U,0,7
53,54,0,1,0,1,1,3001,3001,1,0,13,13,1,25,0,0,단순사무직,3000,5800,2,2,0.0,-,0,0,0,0,0,0,0,0,0,0,30,0,0,0,1000000,20,60000,0,190000,0,60000,3000000,16000000,0,0,17,9800000,21,2,30,1,366,185,R,50000,70000,Y,800000,20123,0,0,0,0,K,U,90000,6
54,55,0,0,2,2,0,9001,6001,0,9001,49,49,3,121,0,0,전문직,5300,11000,4,2,19.0,사무직,5700,0,0,0,0,0,0,0,0,0,49,90미만,37,2000000,0,0,1490000,100000,2990000,390000,2990000,36000000,139000000,1,0,57,3500000,6,7,40,2,882,430,R,50000,60000,Y,0,20112,188,0,0,0,K,U,0,14
55,56,0,1,2,2,0,18001,0,6001,9001,0,0,3,121,0,0,주부,0,7700,2,1,0.0,사무직,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80000,0,80000,0,80000,11000000,11000000,0,0,0,600000,3,0,55,2,1266,104,W,50000,80000,N,600000,20143,7,0,0,0,O,U,250000,15
56,57,0,1,0,0,0,51001,51001,51001,0,25,0,3,121,0,0,자영업,4300,8700,4,2,19.0,운전직,4500,0,0,0,0,0,0,0,0,0,10,10미만,0,0,0,0,390000,0,390000,0,390000,36000000,38000000,0,0,2,4000000,14,2,45,1,63,159,Q,60000,80000,Y,300000,20151,0,0,0,0,O,U,80000,13
57,58,0,0,1,1,0,6001,6001,0,6001,13,13,4,121,0,0,사무직,6500,6500,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,260000,0,260000,260000,26000000,26000000,0,0,6,0,0,0,55,1,139,26,NaN,40000,60000,N,900000,20143,0,0,0,0,O,U,210000,7
58,59,0,0,2,4,2,18001,15001,0,3001,1,25,5,85,0,0,자영업,4700,4700,3,2,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,100,3000000,3000000,0,490000,0,790000,0,490000,16000000,51000000,0,0,2,22800000,0,1,35,2,0,0,NaN,0,0,N,0,20131,0,0,0,0,O,U,0,13
59,60,0,0,2,2,0,21001,21001,0,21001,1,13,0,0,0,0,산업종사자3차,3900,10500,4,2,29.0,3차산업 종사자,5700,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,50000,0,50000,0,790000,12000000,23000000,0,0,0,500000,5,6,50,1,1790,838,NaN,80000,560000,N,1000000,20142,0,0,0,800000,O,U,410000,10
60,61,0,0,1,1,0,1,1,0,1,25,25,4,97,0,0,사무직,4200,8900,3,1,9.0,사무직,4700,0,0,0,0,0,0,0,0,0,2,10미만,0,0,0,0,60000,0,60000,0,490000,10000000,10000000,0,0,2,900000,4,0,35,1,0,0,NaN,10000,20000,N,0,20151,0,0,0,0,K,U,0,7
61,62,0,0,1,2,1,3001,1,0,3001,121,121,2,13,0,0,사무직,4500,4500,3,2,0.0,-,0,0,0,0,0,0,0,0,0,0,7,40미만,100,2000000,2000000,10,0,100000,0,100000,100000,3000000,18000000,0,0,6,200000,0,2,35,2,248,97,R,40000,60000,N,800000,20132,0,0,0,0,K,U,490000,7
62,63,0,1,0,0,0,69001,0,69001,0,0,0,2,49,0,0,산업종사자2차,4200,8500,3,1,29.0,3차산업 종사자,4400,0,0,0,0,0,0,0,0,0,2,0,85,0,0,0,0,0,0,0,0,3000000,3000000,0,0,0,0,0,1,50,2,220,162,NaN,30000,40000,N,300000,20144,0,0,0,0,O,U,100000,9
63,64,0,0,0,1,1,297001,297001,0,0,1,1,2,37,0,0,산업종사자3차,4800,11500,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,23,0,97,2000000,2000000,0,190000,0,190000,0,230000,9000000,9000000,0,0,9,1900000,8,0,35,2,0,0,NaN,10000,20000,N,0,20161,0,0,0,0,O,U,0,10
64,65,0,1,0,0,0,3001,3001,3001,0,1,0,2,73,0,0,사무직,3400,3400,3,2,0.0,-,0,1,201509,7000000,0,0,0,0,5,6,1,0,99,2000000,2000000,0,110000,0,300000,0,110000,12000000,40000000,0,0,0,15300000,46,0,35,2,198,282,R,40000,80000,N,900000,20114,0,0,0,0,K,U,0,7
65,66,0,0,1,1,0,9001,9001,0,9001,1,1,2,121,0,0,공무원,4300,8600,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,38,0,100,6000000,9000000,0,50000,0,50000,0,80000,10000000,10000000,0,0,1,200000,1,1,40,2,1242,217,R,30000,280000,Y,1000000,20132,0,0,0,0,O,U,960000,2
66,67,0,1,3,3,0,99001,3001,90001,6001,1,1,3,49,0,0,단순사무직,4600,9800,4,2,24.0,2차산업 종사자,5200,0,0,0,0,0,0,0,0,0,25,10미만,65,4000000,4000000,0,300000,0,300000,790000,300000,31000000,43000000,0,0,0,2800000,15,0,50,2,76,82,NaN,40000,40000,Y,900000,20124,0,0,0,0,O,U,0,6
67,68,0,0,1,2,1,24001,24001,0,18001,1,13,1,1,0,0,산업종사자3차,4300,9100,4,2,19.0,공무원,4800,1,200112,2000000,2000000,78,0,0,0,0,6,0,0,0,0,0,190000,0,190000,0,190000,27000000,34000000,0,0,0,400000,0,3,55,2,446,248,W,60000,100000,N,900000,20114,0,120000,0,0,K,U,440000,10
68,69,0,1,0,0,0,48001,0,48001,0,0,0,4,121,0,0,산업종사자3차,0,5300,5,2,39.0,주부,0,0,0,0,0,0,0,0,0,0,7,10미만,0,0,0,0,80000,0,100000,0,340000,13000000,15000000,2,0,0,0,0,1,65,1,0,0,NaN,0,0,N,0,20111,1490,0,0,0,O,S,0,10
69,70,0,1,0,0,0,3001,3001,3001,0,1,0,3,109,0,0,자영업,5200,8000,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,4000000,4000000,0,0,0,0,0,1,55,1,140,186,W,30000,40000,Y,0,20123,0,0,0,0,O,U,0,13
70,71,0,1,0,0,0,12001,12001,12001,0,1,0,4,97,0,0,주부,0,4400,3,3,0.0,-,0,0,0,0,0,0,0,0,0,0,4,10미만,0,0,0,0,130000,0,1490000,340000,130000,4000000,139000000,0,0,1,13200000,0,3,30,2,98,46,R,70000,100000,Y,800000,20124,0,0,0,0,O,U,60000,15
71,72,0,1,1,1,0,459001,3001,453001,3001,13,13,6,121,0,0,공무원,5300,11000,4,2,24.0,사무직,5700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,230000,0,80000,14000000,66000000,0,0,0,15400000,3,7,50,1,320,293,E,110000,160000,N,900000,20001,0,0,0,0,K,U,440000,2
72,73,0,1,0,1,1,207001,0,108001,0,0,0,3,121,0,0,자영업,6200,6200,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50000000,50000000,0,0,0,0,0,1,45,1,190,145,E,60000,180000,Y,1000000,20073,0,0,0,0,K,U,0,13
73,74,0,1,0,2,2,111001,111001,105001,0,13,37,4,121,0,0,주부,0,2700,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,1,10미만,0,0,0,0,30000,0,30000,0,300000,1000000,1000000,0,0,1,0,0,0,40,2,356,325,W,60000,80000,N,0,20114,0,80000,0,90000,G,U,220000,15
74,75,0,1,0,2,2,51001,51001,3001,0,1,49,5,97,1,12001,사무직,7000,7000,3,1,0.0,-,0,0,0,0,0,0,0,0,0,0,16,0,0,0,0,0,150000,490000,150000,490000,590000,50000000,50000000,0,0,0,2800000,4,1,45,2,249,0,Q,30000,120000,N,0,20144,0,0,0,0,K,U,0,7
75,76,1,0,1,2,1,1,1,0,1,49,49,1,121,0,0,자영업,5400,6500,1,1,0.0,-,0,1,201301,3000000,0,0,0,0,7,7,9,0,98,2000000,0,10,190000,0,190000,0,390000,12000000,12000000,0,0,6,0,0,0,45,1,372,185,R,70000,300000,N,0,20102,8,0,0,0,G,U,110000,13
76,77,0,1,0,0,0,183001,0,183001,0,49,0,4,121,0,0,자영업,5400,6700,2,1,0.0,주부,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6000000,6000000,0,0,0,0,1,1,40,1,141,272,W,40000,70000,Y,800000,20123,0,0,0,0,O,U,840000,13
77,78,0,0,1,1,0,6001,6001,0,6001,1,1,1,13,0,0,산업종사자3차,4000,10300,5,1,24.0,3차산업 종사자,5000,2,201412,20000000,10000000,0,0,0,5,4,2,0,94,6000000,0,0,390000,0,390000,0,590000,37000000,37000000,0,0,3,400000,3,0,50,2,163,220,W,30000,50000,N,900000,20112,0,0,0,0,O,U,120000,10
78,79,0,2,0,0,0,153001,18001,153001,0,37,0,6,121,0,0,단순사무직,3900,8500,5,1,14.0,전문직,4600,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,100000,0,100000,0,100000,9000000,9000000,0,0,3,600000,1,0,45,2,168,0,W,30000,140000,Y,800000,20111,0,0,0,0,O,U,0,6
79,80,0,0,0,1,1,9001,9001,0,0,0,1,0,0,0,0,자영업,4700,4700,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,90000,6000000,6000000,0,0,0,0,0,1,40,1,56,215,R,70000,300000,N,800000,20134,0,0,0,0,O,U,540000,13
80,81,0,0,1,1,0,30001,30001,0,30001,1,1,2,109,0,0,주부,0,5700,3,2,19.0,-,0,3,200202,16000000,7000000,63,24,0,4,4,22,10미만,94,3000000,2000000,30,300000,110000,490000,790000,790000,13000000,25000000,0,0,7,18500000,31,0,60,2,0,0,NaN,30000,0,N,0,20161,0,0,0,0,NaN,U,0,15
81,82,0,1,0,1,1,24001,24001,18001,0,49,49,3,73,0,0,공무원,4800,14900,2,1,0.0,기업/단체 임원,9900,0,0,0,0,0,0,0,0,0,1,30미만,0,0,0,0,30000,150000,30000,150000,230000,47000000,47000000,0,0,3,0,0,1,55,2,194,29,NaN,50000,140000,N,900000,20132,0,0,0,0,O,U,0,2
82,83,0,1,0,0,0,1,0,1,0,0,0,5,121,0,0,주부,0,8400,1,1,0.0,-,0,0,0,0,0,0,0,0,0,0,15,40미만,0,0,0,0,0,0,0,0,1490000,54000000,54000000,0,0,17,0,0,2,60,2,111,97,W,30000,50000,Y,700000,20132,0,0,0,0,K,U,30000,15

In [19]:
data['MATE_OCCP_NAME_G'] = data['MATE_OCCP_NAME_G'].replace('*', 'missing')

In [20]:
data['MATE_OCCP_NAME_G'] = data['MATE_OCCP_NAME_G'].replace(np.nan, '-')

In [22]:
data['MATE_OCCP_NAME_G'] = data['MATE_OCCP_NAME_G'].replace(' ', '', regex=True)

In [39]:
# 직업별 평균 소득
occp_incm = pd.DataFrame()
occp_incm['mean'] = data.groupby('OCCP_NAME_G')['CUST_JOB_INCM'].mean().round(2)

# 직업별 가구수 / 배우자 추정 소득 / 신용대출건수 / 신용대출금액 / 신용상환금액 / 최초신용등륵 / 최근신용등급 / 연체율
occp_incm['mean_fmly_num'] = data.groupby('OCCP_NAME_G')['ACTL_FMLY_NUM'].mean().round(2)
occp_incm['mean_mate_incm'] = data.groupby('OCCP_NAME_G')['MATE_JOB_INCM'].mean().round(2)
occp_incm['mean_loan_cnt'] = data.groupby('OCCP_NAME_G')['CRDT_LOAN_CNT'].mean().round(2)
occp_incm['mean_crnl_amt'] = data.groupby('OCCP_NAME_G')['TOT_CRLN_AMT'].mean().round(2)
occp_incm['mean_crdt_amt'] = data.groupby('OCCP_NAME_G')['TOT_REPY_AMT'].mean().round(2)
occp_incm['mean_balance_rate'] = (1 - (occp_incm['mean_crdt_amt'] / occp_incm['mean_crnl_amt'])) * 100
occp_incm['mean_start_crdt'] = data.groupby('OCCP_NAME_G')['STRT_CRDT_GRAD'].mean().round(2)
occp_incm['mean_ltst_crdt'] = data.groupby('OCCP_NAME_G')['LTST_CRDT_GRAD'].mean().round(2)
occp_incm['mean_ovdu_rate'] = data.groupby('OCCP_NAME_G')['PREM_OVDU_RATE'].mean().round(2)

In [40]:
occp_incm

,mean,mean_fmly_num,mean_mate_incm,mean_loan_cnt,mean_crnl_amt,mean_crdt_amt,mean_balance_rate,mean_start_crdt,mean_ltst_crdt,mean_ovdu_rate
OCCP_NAME_G,,,,,,,,,,
missing,3339.26,2.75,2064.19,0.07,508771.93,474894.13,6.658740,0.01,0.06,6.84
고소득전문직,6223.55,2.16,1128.78,0.05,465249.39,399836.47,14.059754,0.02,0.05,3.83
공무원,4189.55,2.48,1524.51,0.05,577096.84,489098.41,15.248469,0.03,0.06,4.22
기업_단체임원,6808.45,2.76,1213.45,0.09,951008.65,689721.42,27.474748,0.10,0.20,6.23
기타,0.00,2.63,247.25,0.21,1379186.60,1186004.78,14.006939,0.08,0.28,7.34
단순노무직,2435.81,2.72,1093.30,0.23,1549330.09,1068209.50,31.053459,0.30,0.49,9.22
단순사무직,3947.21,2.75,2178.99,0.16,1098855.61,765765.77,30.312430,0.17,0.31,8.28
사무직,4524.72,2.47,1128.88,0.10,833845.97,639406.55,23.318386,0.08,0.17,6.56
산업종사자1차,2995.67,3.12,1118.93,0.14,1123089.98,801358.23,28.647015,0.14,0.28,9.33
산업종사자2차,4014.71,2.79,1128.79,0.18,1325070.31,941985.21,28.910549,0.19,0.36,8.72
산업종사자3차,3492.35,2.86,1796.18,0.25,1740181.27,1234924.47,29.034722,0.26,0.49,10.61
예체능계종사자,3826.18,2.55,985.58,0.18,1305555.56,963675.21,26.186580,0.20,0.32,8.93
운전직,3959.08,2.89,991.53,0.18,1262935.09,932267.17,26.182495,0.19,0.42,9.39
자영업,4207.27,2.94,1780.91,0.22,1870848.71,1295202.95,30.769231,0.23,0.44,9.64
전문직,4273.69,2.47,1208.84,0.11,765417.41,572278.41,25.233160,0.10,0.19,6.66
주부,6.35,3.01,2766.94,0.21,1338327.59,1002793.40,25.071155,0.17,0.35,8.21
학생,22.14,2.26,65.11,0.02,105345.50,78748.37,25.247524,0.02,0.03,8.93